name: Build MCAddon Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run Compiler
        id: build
        run: |
          OUTPUT=$(node compile.js)

          echo "$OUTPUT"

          echo "build_output<<EOF" >> $GITHUB_OUTPUT
          echo "$OUTPUT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Get Version
        id: version
        run: |
          VERSION=$(node -e "console.log(require('./manifest.json').header.version.join('.'))")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Get mcpack
        id: mcpack
        run: |
          FILE=$(find . -name "*.mcpack" | head -n 1)
          echo "file=$FILE" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: SAME Build v${{ steps.version.outputs.version }}

          body: |
            Automated SAME Compiler Build

            ${{ steps.build.outputs.build_output }}

          files: |
            ${{ steps.mcpack.outputs.file }}
